# Generated by Django 3.1.5 on 2021-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210219_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtegory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
