# Generated by Django 3.1.5 on 2021-02-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_subtegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subtegory',
            new_name='subcategory',
        ),
    ]
